'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { CustomerFooter } from '@/components/ui';
import { apiClient, apiError, type ApiOrder } from '@/lib/apiClient';
import { useCartStore } from '@/lib/store/cartStore';

const icon = (name: string, classes = '') => <span className={`material-symbols-outlined ${classes}`}>{name}</span>;
const money = (amount: number) => `Rs ${amount.toLocaleString('en-PK')}`;
const ongoing = ['New', 'Preparing', 'Out for Delivery'];
type Filter = 'all' | 'ongoing' | 'completed' | 'cancelled';

export default function Orders() {
  const [orders, setOrders] = useState<ApiOrder[]>([]); const [filter, setFilter] = useState<Filter>('all'); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  const add = useCartStore((state) => state.add);
  useEffect(() => { apiClient.get('/orders').then((response) => setOrders(response.data.data)).catch((requestError) => setError(apiError(requestError))).finally(() => setLoading(false)); }, []);
  const visible = useMemo(() => orders.filter((order) => filter === 'all' || filter === 'ongoing' && ongoing.includes(order.status) || filter === 'completed' && order.status === 'Delivered' || filter === 'cancelled' && order.status === 'Cancelled'), [filter, orders]);
  const reorder = (order: ApiOrder) => { order.items.forEach((line) => { if (typeof line.item !== 'string') for (let quantity = 0; quantity < line.quantity; quantity += 1) add(line.item); }); };
  const current = orders.find((order) => ongoing.includes(order.status));

  return <><section className="mx-auto max-w-[1440px] px-5 py-7 md:px-7 md:py-12"><div className="hidden md:block"><p className="text-sm text-neutral-copy">Account <span className="mx-2">›</span> <span className="font-semibold text-orange-800">Orders</span></p><h1 className="mt-3 font-display text-[29px] font-semibold text-neutral-ink">Order History</h1><p className="mt-2 text-[17px] text-neutral-copy">Manage and track your recent cravings from Karachi&apos;s best kitchens.</p></div><div className="md:hidden"><h1 className="font-display text-[28px] font-semibold text-neutral-ink">Order History</h1><MobileFilters filter={filter} setFilter={setFilter} /></div>{error ? <p className="mt-8 rounded-xl bg-danger/10 p-4 text-danger">{error}</p> : loading ? <div className="mt-8 h-72 animate-pulse rounded-2xl bg-neutral-soft" /> : <div className="mt-10 grid gap-12 md:grid-cols-[292px_minmax(0,1fr)]"><aside className="hidden md:block"><DesktopFilters orders={orders} filter={filter} setFilter={setFilter} />{current && <CurrentOrder order={current} />}</aside><div className="space-y-5 md:space-y-7">{visible.length ? visible.map((order) => <OrderCard key={order._id} order={order} onReorder={() => reorder(order)} />) : <div className="rounded-2xl bg-white p-10 text-center text-neutral-copy shadow-card">No orders in this category yet.</div>}<button className="mx-auto hidden h-[84px] w-[350px] items-center justify-center gap-4 rounded-xl border-2 border-orange-100 font-semibold text-orange-800 md:flex">Load More Orders {icon('expand_more')}</button></div></div>}</section><div className="hidden md:block"><CustomerFooter /></div><MobileNav /></>;
}

function MobileFilters({ filter, setFilter }: { filter: Filter; setFilter: (filter: Filter) => void }) { const tabs: [Filter, string][] = [['all', 'All Orders'], ['ongoing', 'In Progress'], ['completed', 'Completed']]; return <div className="mt-3 flex gap-2 overflow-x-auto pb-2">{tabs.map(([value, label]) => <button key={value} onClick={() => setFilter(value)} className={`shrink-0 rounded-full px-5 py-2 text-[16px] font-semibold ${filter === value ? 'bg-orange-800 text-white' : 'bg-[#dce2f3] text-neutral-copy'}`}>{label}</button>)}</div>; }
function DesktopFilters({ orders, filter, setFilter }: { orders: ApiOrder[]; filter: Filter; setFilter: (filter: Filter) => void }) { const filters: [Filter, string, string][] = [['all', 'All Orders', 'receipt_long'], ['ongoing', 'Ongoing', 'more_horiz'], ['completed', 'Completed', 'check_circle'], ['cancelled', 'Cancelled', 'cancel']]; return <><div className="rounded-2xl bg-white p-7 shadow-card"><h2 className="text-[15px] font-semibold uppercase tracking-wide text-neutral-warm">Quick Filters</h2><div className="mt-6 space-y-2">{filters.map(([value, label, symbol]) => <button key={value} onClick={() => setFilter(value)} className={`flex w-full items-center gap-4 rounded-xl px-5 py-4 text-left transition ${filter === value ? 'bg-orange-500 text-white' : 'text-neutral-copy hover:bg-neutral-soft'}`}>{icon(symbol, 'text-[21px]')}<span className="flex-1 font-medium">{label}</span><span className={`rounded px-2 py-0.5 text-xs ${filter === value ? 'bg-orange-800/20' : 'bg-[#dce2f3]'}`}>{value === 'all' ? orders.length : value === 'ongoing' ? orders.filter((order) => ongoing.includes(order.status)).length : orders.filter((order) => value === 'completed' ? order.status === 'Delivered' : order.status === 'Cancelled').length}</span></button>)}</div></div></>; }
function CurrentOrder({ order }: { order: ApiOrder }) { return <div className="mt-7 rounded-2xl bg-[#283343] p-7 text-white shadow-float"><div className="flex items-center gap-3 text-sm font-semibold">{icon('local_shipping', 'text-[23px]')}Current Order</div><h3 className="mt-7 font-display text-[24px] font-semibold leading-8">{order.status === 'Preparing' ? 'Preparing Your Feast' : 'Your order is on the way'}</h3><p className="mt-6 text-sm text-[#dce2f3]">ETA: 25–30 mins · {restaurant(order)}</p><div className="mt-5 h-2 overflow-hidden rounded-full bg-[#6b7280]"><div className="h-full w-2/5 bg-orange-500" /></div><Link href={`/orders/${order._id}/track`} className="mt-5 flex h-16 items-center justify-center rounded-lg bg-white font-semibold text-neutral-ink">Track Real-time</Link></div>; }
function OrderCard({ order, onReorder }: { order: ApiOrder; onReorder: () => void }) { const isCancelled = order.status === 'Cancelled'; const isOngoing = ongoing.includes(order.status); const first = order.items[0]; const image = first && typeof first.item !== 'string' ? first.item.imageUrl : ''; const label = restaurant(order); const orderLabel = `#ORD-${order._id.slice(-4).toUpperCase()}`; const date = new Date(order.createdAt).toLocaleDateString('en-PK', { day: '2-digit', month: 'short', year: 'numeric' }); return <article className={`overflow-hidden rounded-2xl border bg-white shadow-card ${isOngoing ? 'border-l-4 border-l-orange-500' : 'border-transparent'}`}><div className="flex gap-5 p-5 md:items-center md:p-7"><img src={image} alt="" className={`size-[108px] shrink-0 rounded-xl object-cover md:size-[108px] ${isCancelled ? 'grayscale opacity-60' : ''}`} /><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="font-semibold text-orange-800 md:hidden">{orderLabel}</p><h2 className={`truncate font-display text-[23px] font-semibold md:text-[25px] ${isCancelled ? 'text-neutral-muted' : ''}`}>{label}</h2><p className="mt-1 text-[16px] text-neutral-copy md:hidden">{order.items.reduce((sum, item) => sum + item.quantity, 0)} Items · {date}</p><p className="mt-1 hidden text-[15px] text-neutral-copy md:block">Order {orderLabel} · {date}</p></div><Status status={order.status} /></div><p className="mt-2 hidden truncate text-[16px] text-neutral-copy md:block">{itemsCopy(order)}</p><p className={`mt-3 font-display text-[25px] font-semibold text-orange-800 md:text-[24px] ${isCancelled ? 'line-through text-neutral-muted' : ''}`}>{money(order.total)}</p></div><div className="hidden w-[180px] shrink-0 gap-4 md:flex md:flex-col"><button onClick={onReorder} disabled={isCancelled} className="h-12 rounded-lg bg-orange-800 font-medium text-white disabled:bg-[#dce2f3] disabled:text-neutral-copy">Reorder</button><Link href={isOngoing ? `/orders/${order._id}/track` : `/order-confirmation/${order._id}`} className="flex h-12 items-center justify-center rounded-lg border border-neutral-warm text-neutral-ink">{isOngoing ? 'Track Order' : 'View Details'}</Link></div></div><div className="flex gap-5 border-t border-neutral-border/50 px-5 py-4 md:hidden">{isOngoing ? <Link href={`/orders/${order._id}/track`} className="flex h-[70px] flex-1 items-center justify-center rounded-xl bg-orange-800 font-semibold text-white">Track Order</Link> : <button onClick={onReorder} disabled={isCancelled} className="h-[70px] flex-1 rounded-xl bg-orange-800 font-semibold text-white disabled:bg-[#dce2f3] disabled:text-neutral-copy">Reorder</button>}<Link href={`/order-confirmation/${order._id}`} className="flex h-[70px] w-[90px] items-center justify-center rounded-xl border border-neutral-warm font-semibold text-neutral-copy">{order.status === 'Delivered' ? 'Rate' : 'Help'}</Link></div></article>; }
function Status({ status }: { status: ApiOrder['status'] }) { const styles = { New: 'bg-[#dce2f3] text-neutral-copy', Preparing: 'bg-[#dce2f3] text-neutral-copy', 'Out for Delivery': 'bg-orange-100 text-orange-800', Delivered: 'bg-[#dcfce7] text-[#166534]', Cancelled: 'bg-[#fee2e2] text-[#b91c1c]' }; return <span className={`shrink-0 rounded-lg px-3 py-1.5 text-[13px] font-semibold uppercase md:normal-case ${styles[status]}`}>{status === 'Out for Delivery' ? 'On the way' : status}</span>; }
function restaurant(order: ApiOrder) { const first = order.items[0]; return first && typeof first.item !== 'string' ? first.item.name : 'Orange Kitchen'; }
function itemsCopy(order: ApiOrder) { return order.items.map((line) => `${line.quantity}x ${typeof line.item === 'string' ? 'Menu item' : line.item.name}`).join(', '); }
function MobileNav() { return <nav className="fixed inset-x-0 bottom-0 z-30 flex h-[84px] items-center justify-around rounded-t-2xl bg-white shadow-header md:hidden"><Link href="/" className="flex flex-col items-center gap-1 text-neutral-copy">{icon('home', 'text-[25px]')}<span>Home</span></Link><Link href="/menu" className="flex flex-col items-center gap-1 text-neutral-copy">{icon('search', 'text-[25px]')}<span>Search</span></Link><Link href="/profile/orders" className="flex flex-col items-center gap-1 rounded-xl bg-orange-500 px-5 py-2 text-orange-900">{icon('receipt_long', 'text-[25px]')}<span>Orders</span></Link><Link href="/profile" className="flex flex-col items-center gap-1 text-neutral-copy">{icon('person', 'text-[25px]')}<span>Profile</span></Link></nav>; }
