'use client';

import Link from 'next/link';
import { type MouseEvent, useEffect, useRef, useState } from 'react';
import { CustomerFooter, CustomerNavBar } from '@/components/ui';
import { BlurImage, PageLoader, ProductCard, ScrollReveal, SectionHeading } from '@/components/storefront/Experience';
import { apiClient, type ApiCategory, type ApiHeroSlide, type ApiMenuItem } from '@/lib/apiClient';
import { useCartStore } from '@/lib/store/cartStore';

const images = { burger: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1000&q=82', rice: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=1000&q=82', bbq: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1000&q=82' };
const fallbackMenu = [['Mighty Zinger', 'Classic crispy burger with cheese & mayo', 650, images.burger, 'Fast Food'], ['Beef Seekh Kabab', 'Tender, spiced beef skewers', 890, images.bbq, 'BBQ'], ['Egg Fried Rice', 'Wok-tossed rice with vegetables', 550, images.rice, 'Chinese Food'], ['Chicken Chow Mein', 'Traditional stir-fry with spicy sauce', 720, images.rice, 'Chinese Food']].map(([name, description, price, imageUrl, category], i) => ({ _id: `featured-${i}`, name, description, price, imageUrl, category } as unknown as ApiMenuItem));
const categoryMeta: Record<string, { image: string; tag: string }> = { 'Fast Food': { image: images.burger, tag: 'Crispy, stacked, satisfying' }, 'Chinese Food': { image: images.rice, tag: 'Wok-tossed comfort' }, BBQ: { image: images.bbq, tag: 'Smoky grill favourites' } };
const defaultSlides: ApiHeroSlide[] = [
  { _id: 'hero-1', title: "Karachi's finest", highlightedText: 'at your door.', subtitle: 'Freshly made favourites from our cloud kitchen, delivered to your table.', ctaLabel: 'Explore the menu', isActive: true, displayOrder: 0, imageUrl: 'https://images.unsplash.com/photo-1701579231305-d84d8af9a3fd?auto=format&fit=crop&w=1800&q=85' },
  { _id: 'hero-2', title: 'Fresh from our', highlightedText: 'cloud kitchen.', subtitle: 'Generous portions, bold flavours, and the warmth of a proper Karachi meal.', ctaLabel: 'Order now', isActive: true, displayOrder: 1, imageUrl: images.bbq },
  { _id: 'hero-3', title: 'Big flavour,', highlightedText: 'made fresh.', subtitle: 'Crispy, juicy and finished with our signature sauces.', ctaLabel: 'See favourites', isActive: true, displayOrder: 2, imageUrl: images.burger },
];
type Flyer = { x: number; y: number; dx: number; dy: number; flying: boolean };

export default function HomePage() {
  const [menu, setMenu] = useState<ApiMenuItem[]>(fallbackMenu); const [categories, setCategories] = useState<ApiCategory[]>([]); const [slides, setSlides] = useState(defaultSlides); const [tab, setTab] = useState('All'); const [search, setSearch] = useState(''); const [notice, setNotice] = useState(''); const [ready, setReady] = useState(false); const [flyer, setFlyer] = useState<Flyer | null>(null); const [addressOpen, setAddressOpen] = useState(false); const add = useCartStore((s) => s.add);
  useEffect(() => { const reveal = window.setTimeout(() => setReady(true), 600); Promise.all([apiClient.get('/menu'), apiClient.get('/categories'), apiClient.get('/hero-slides')]).then(([m, c, h]) => { if (m.data.data?.length) setMenu(m.data.data); setCategories(c.data.data ?? []); const active = (h.data.data ?? []).filter((slide: ApiHeroSlide) => slide.isActive); if (active.length) setSlides(active); }).catch(() => undefined); return () => window.clearTimeout(reveal); }, []);
  useEffect(() => { if (!window.localStorage.getItem('orange-delivery-address')) setAddressOpen(true); }, []);
  const addItem = (item: ApiMenuItem, e: MouseEvent<HTMLButtonElement>) => { add(item); setNotice(`${item.name} added to your cart`); window.setTimeout(() => setNotice(''), 2000); const a = e.currentTarget.getBoundingClientRect(), b = document.querySelector('[aria-label="Cart"]')?.getBoundingClientRect(); if (!b) return; setFlyer({ x: a.left + a.width / 2, y: a.top + a.height / 2, dx: b.left - a.left, dy: b.top - a.top, flying: false }); requestAnimationFrame(() => setFlyer((v) => v && { ...v, flying: true })); window.setTimeout(() => setFlyer(null), 650); };
  const matches = menu.filter((item) => `${item.name} ${item.description}`.toLowerCase().includes(search.toLowerCase())); const picks = (tab === 'All' ? menu : menu.filter((x) => tab === 'Vegetarian' ? /rice|vegetable|naan/i.test(x.name) : x.name.length % 2 === (tab === 'Best Sellers' ? 0 : 1))).slice(0, 8);
  return <main className="storefront"><PageLoader ready={ready} /><CustomerNavBar fixed onSearch={setSearch} onLocationClick={() => setAddressOpen(true)} locationName="Karachi" /><HeroCarousel slides={slides} />
    <ScrollReveal><section className="store-section"><SectionHeading eyebrow="Made for cravings" title="Explore cuisines" copy="A little something for every mood." action={<Link href="/menu" className="text-link">View menu <span>→</span></Link>} /><div className="cuisine-grid">{(categories.length ? categories : Object.keys(categoryMeta).map((name, displayOrder) => ({ _id: name, name, displayOrder } as ApiCategory))).slice(0, 3).map((category, index) => { const meta = categoryMeta[category.name] ?? categoryMeta.BBQ; return <Link key={category._id} href={`/menu?category=${category._id}`} className="cuisine-card" style={{ transitionDelay: `${index * 90}ms` }}><BlurImage src={meta.image} alt={`${category.name} cuisine`} sizes="(max-width: 767px) 48vw, 33vw" /><div><small>Explore</small><h3>{category.name}</h3><p>{meta.tag}</p><span className="cuisine-card__arrow">→</span></div></Link>; })}</div></section></ScrollReveal>
    <section className="store-section store-section--soft"><ScrollReveal><SectionHeading eyebrow="Most loved" title={search ? `Results for “${search}”` : 'Popular right now'} copy={search ? `${matches.length} dish${matches.length === 1 ? '' : 'es'} found` : 'The dishes Karachi keeps coming back for.'} action={!search ? <Link href="/menu" className="text-link">See all <span>→</span></Link> : undefined} /><div className="product-grid">{(search ? matches : menu).slice(0, 8).map((item, index) => <ProductCard key={item._id} item={item} rating={(4.6 + (index % 4) / 10).toFixed(1)} onAdd={(e) => addItem(item, e)} />)}</div>{search && !matches.length && <p className="empty-state">No dishes match that search. Try a cuisine or dish name.</p>}</ScrollReveal></section>
    <ScrollReveal><section className="store-section"><SectionHeading eyebrow="Chosen for you" title="Top picks" copy="Freshly prepared, ready when you are." /><div className="filter-row" role="tablist" aria-label="Top picks filter">{['All', 'Best Sellers', 'New Arrival', 'Vegetarian'].map((name) => <button key={name} type="button" role="tab" aria-selected={tab === name} onClick={() => setTab(name)} className={tab === name ? 'is-active' : ''}>{name}</button>)}</div><div className="product-grid product-grid--picks">{picks.map((item, index) => <ProductCard key={item._id} item={item} rating={(4.5 + (index % 4) / 10).toFixed(1)} onAdd={(e) => addItem(item, e)} />)}</div>{!picks.length && <p className="empty-state">No dishes in this collection just yet.</p>}</section></ScrollReveal>
    <ScrollReveal><section className="promo-section"><div><span className="eyebrow">Orange kitchen notes</span><h2>Big flavour. Made on demand.</h2><p>Every dish is prepared after you order, so it arrives exactly how it should.</p><Link href="/menu" className="promo-section__cta">Choose your favourites <span>→</span></Link></div><BlurImage src={images.bbq} alt="Freshly grilled Orange favourites" sizes="(max-width: 767px) 100vw, 50vw" /></section></ScrollReveal>
    <CustomerFooter /><AddressModal open={addressOpen} onClose={() => setAddressOpen(false)} onSave={(value) => { window.localStorage.setItem('orange-delivery-address', value); setAddressOpen(false); }} />
    {flyer && <span className="cart-flyer" style={{ left: flyer.x, top: flyer.y, transform: flyer.flying ? `translate(${flyer.dx}px, ${flyer.dy}px) scale(.4)` : 'translate(-50%, -50%)', opacity: flyer.flying ? .2 : 1 }}><span className="material-symbols-outlined">shopping_bag</span></span>}{notice && <div className="cart-notice" role="status">{notice}</div>}
  </main>;
}

function HeroCarousel({ slides }: { slides: ApiHeroSlide[] }) { const [active, setActive] = useState(0); const [paused, setPaused] = useState(false); const start = useRef<number | null>(null); useEffect(() => setActive(0), [slides.length]); useEffect(() => { if (paused || slides.length < 2) return; const id = window.setInterval(() => setActive((v) => (v + 1) % slides.length), 5200); return () => window.clearInterval(id); }, [paused, slides.length]); const go = (n: number) => setActive((n + slides.length) % slides.length); const slide = slides[active] ?? defaultSlides[0]; return <section className="hero-carousel" aria-roledescription="carousel" aria-label="Featured Orange offers" onMouseEnter={() => setPaused(true)} onMouseLeave={() => setPaused(false)} onTouchStart={(e) => { start.current = e.touches[0].clientX; setPaused(true); }} onTouchEnd={(e) => { if (start.current !== null && Math.abs(e.changedTouches[0].clientX - start.current) > 40) go(active + (e.changedTouches[0].clientX < start.current ? 1 : -1)); start.current = null; setPaused(false); }} onKeyDown={(e) => { if (e.key === 'ArrowLeft') go(active - 1); if (e.key === 'ArrowRight') go(active + 1); }} tabIndex={0}><div className="hero-carousel__image" key={slide._id}><BlurImage src={slide.imageUrl} alt="Fresh Orange Cloud Kitchen food" priority sizes="100vw" /></div><div className="hero-carousel__shade" /><div className="hero-carousel__content" key={`${slide._id}-copy`}><span>Fresh from Orange</span><h1>{slide.title} <em>{slide.highlightedText}</em></h1><p>{slide.subtitle}</p><Link href="/menu">{slide.ctaLabel} <span>→</span></Link></div><button type="button" className="hero-carousel__arrow hero-carousel__arrow--prev" onClick={() => go(active - 1)} aria-label="Previous offer"><span className="material-symbols-outlined">arrow_back</span></button><button type="button" className="hero-carousel__arrow hero-carousel__arrow--next" onClick={() => go(active + 1)} aria-label="Next offer"><span className="material-symbols-outlined">arrow_forward</span></button><div className="hero-carousel__dots">{slides.map((s, i) => <button key={s._id} type="button" onClick={() => go(i)} aria-label={`Show offer ${i + 1}`} aria-current={i === active}><i /></button>)}</div></section>; }

function AddressModal({ open, onClose, onSave }: { open: boolean; onClose: () => void; onSave: (value: string) => void }) { const [value, setValue] = useState('Karachi, Pakistan'); if (!open) return null; return <div className="fixed inset-0 z-[70] grid place-items-center bg-black/55 p-4" role="dialog" aria-modal="true" aria-labelledby="address-title"><section className="w-full max-w-md rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><span className="grid size-11 place-items-center rounded-2xl bg-orange-100 text-orange-800"><span className="material-symbols-outlined">location_on</span></span><h2 id="address-title" className="mt-4 font-display text-2xl font-bold">Where should we deliver?</h2><p className="mt-2 text-sm text-neutral-copy">Orange is currently available in Karachi only.</p></div><button type="button" onClick={onClose} aria-label="Close address selector" className="grid size-11 place-items-center rounded-full hover:bg-neutral-soft"><span className="material-symbols-outlined">close</span></button></div><label className="mt-6 block text-sm font-semibold">Karachi delivery address<input value={value} onChange={(e) => setValue(e.target.value)} className="mt-2 w-full rounded-xl border border-neutral-border px-4 py-3 font-normal outline-none focus:border-orange-500 focus:ring-2 focus:ring-orange-500/20" /></label><button type="button" onClick={() => onSave(value)} className="mt-6 min-h-12 w-full rounded-xl bg-orange-500 font-bold text-white transition hover:bg-orange-800">Confirm address</button></section></div>; }
