'use client';

import { useRouter } from 'next/navigation';
import { useState } from 'react';
import axios from 'axios';
import Link from 'next/link';
import { AuthPhoneField, AuthShell, ContinueButton, Terms } from '@/components/auth/AuthShell';
import { apiClient, apiError } from '@/lib/apiClient';
import { useAuthStore } from '@/lib/store/authStore';

export default function Login() {
  const router = useRouter(); const setSession = useAuthStore((state) => state.setSession);
  const [phone, setPhone] = useState(''); const [otp, setOtp] = useState(''); const [developmentOtp, setDevelopmentOtp] = useState(''); const [step, setStep] = useState<'phone' | 'otp'>('phone'); const [error, setError] = useState(''); const [showSignup, setShowSignup] = useState(false); const [loading, setLoading] = useState(false);
  const submit = async () => { if (step === 'phone' && !phone.trim()) { setError('Phone number is required.'); return; } if (step === 'otp' && otp.length !== 6) { setError('Enter the six-digit verification code.'); return; } setLoading(true); setError(''); setShowSignup(false); try { if (step === 'phone') { const response = await apiClient.post('/auth/login', { phone }); setDevelopmentOtp(response.data.data.developmentOtp ?? ''); setStep('otp'); } else { const response = await apiClient.post('/auth/verify-otp', { phone, otp, purpose: 'login' }); setSession(response.data.data.accessToken, response.data.data.user); router.push('/'); } } catch (requestError) { setError(apiError(requestError)); setShowSignup(axios.isAxiosError(requestError) && requestError.response?.data?.error?.code === 'USER_NOT_FOUND'); } finally { setLoading(false); } };
  return <AuthShell>{step === 'phone' ? <div className="flex flex-col md:min-h-0"><div><h2 className="font-display text-[28px] font-semibold text-neutral-ink">Welcome Back</h2><p className="mt-2 text-[17px] text-neutral-copy">Login or Sign up to start your feast.</p><div className="mt-8"><AuthPhoneField value={phone} onChange={setPhone} /></div><div className="mt-6 md:hidden"><Terms /></div></div><div className="mt-8"><ContinueButton loading={loading} onClick={submit}>Continue</ContinueButton><div className="mt-6 hidden md:block"><Terms /></div></div>{error && <p className="mt-4 text-center text-sm text-danger">{error}</p>}{showSignup && <Link href="/signup" className="mt-4 flex h-12 items-center justify-center rounded-lg border border-orange-800 font-semibold text-orange-800 transition hover:bg-orange-100">Create an account</Link>}</div> : <OtpStep phone={phone} otp={otp} setOtp={setOtp} developmentOtp={developmentOtp} error={error} loading={loading} onBack={() => setStep('phone')} onSubmit={submit} />}</AuthShell>;
}

function OtpStep({ phone, otp, setOtp, developmentOtp, error, loading, onBack, onSubmit }: { phone: string; otp: string; setOtp: (value: string) => void; developmentOtp: string; error: string; loading: boolean; onBack: () => void; onSubmit: () => void }) { return <div><button onClick={onBack} className="flex items-center gap-2 font-semibold text-orange-800"><span className="material-symbols-outlined">arrow_back</span>Change phone number</button><h2 className="mt-10 font-display text-[38px] font-semibold text-neutral-ink md:text-[31px]">Verify Identity</h2><p className="mt-3 text-[18px] text-neutral-copy">Enter the six-digit code sent to +92 {phone}.</p><label className="mt-12 block"><span className="mb-3 block font-semibold">Verification code</span><input value={otp} onChange={(event) => setOtp(event.target.value.replace(/\D/g, '').slice(0, 6))} inputMode="numeric" autoFocus maxLength={6} className="h-20 w-full rounded-xl border border-[#e0c0b1] bg-white px-5 text-center font-display text-[30px] tracking-[.45em] outline-none focus:border-orange-500" /></label>{developmentOtp && <p className="mt-4 rounded-xl bg-orange-100/50 p-3 text-center text-sm text-orange-900">Development OTP: <b>{developmentOtp}</b></p>}{error && <p className="mt-4 text-center text-sm text-danger">{error}</p>}<div className="mt-10"><ContinueButton loading={loading} onClick={onSubmit}>Verify & Continue</ContinueButton></div></div>; }
