'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { AuthPhoneField, AuthShell, ContinueButton, Terms } from '@/components/auth/AuthShell';
import { apiClient, apiError } from '@/lib/apiClient';
import { useAuthStore } from '@/lib/store/authStore';

export default function Signup() {
  const router = useRouter(); const setSession = useAuthStore((state) => state.setSession);
  const [name, setName] = useState(''); const [phone, setPhone] = useState(''); const [otp, setOtp] = useState(''); const [developmentOtp, setDevelopmentOtp] = useState(''); const [step, setStep] = useState<'form' | 'otp'>('form'); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const submit = async () => { setLoading(true); setError(''); try { if (step === 'form') { const response = await apiClient.post('/auth/signup', { name, phone }); setDevelopmentOtp(response.data.data.developmentOtp ?? ''); setStep('otp'); } else { const response = await apiClient.post('/auth/verify-otp', { phone, otp, purpose: 'signup' }); setSession(response.data.data.accessToken, response.data.data.user); router.push('/'); } } catch (requestError) { setError(apiError(requestError)); } finally { setLoading(false); } };
  return <AuthShell>{step === 'form' ? <div className="flex flex-col md:min-h-0"><div><h2 className="font-display text-[30px] font-semibold text-neutral-ink md:text-[31px]">Create your account</h2><p className="mt-2 text-[18px] text-neutral-copy">Sign up to start your feast.</p><label className="mt-8 block"><span className="mb-2 block text-[16px] font-semibold text-neutral-copy">Full Name</span><input value={name} onChange={(event) => setName(event.target.value)} placeholder="Your name" className="h-14 w-full rounded-xl border border-[#e0c0b1] bg-white px-5 text-lg outline-none focus:border-orange-500" /></label><div className="mt-5"><AuthPhoneField value={phone} onChange={setPhone} /></div><div className="mt-7 md:hidden"><Terms /></div></div><div className="mt-9 md:mt-6"><ContinueButton loading={loading} onClick={submit}>Continue</ContinueButton><p className="mt-5 text-center text-sm text-neutral-copy">Already have an account? <Link href="/login" className="font-semibold text-orange-800">Log in</Link></p><div className="mt-6 hidden md:block"><Terms /></div></div>{error && <p className="mt-4 text-center text-sm text-danger">{error}</p>}</div> : <SignupOtp phone={phone} otp={otp} setOtp={setOtp} developmentOtp={developmentOtp} error={error} loading={loading} onBack={() => setStep('form')} onSubmit={submit} />}</AuthShell>;
}

function SignupOtp({ phone, otp, setOtp, developmentOtp, error, loading, onBack, onSubmit }: { phone: string; otp: string; setOtp: (value: string) => void; developmentOtp: string; error: string; loading: boolean; onBack: () => void; onSubmit: () => void }) { return <div><button onClick={onBack} className="flex items-center gap-2 font-semibold text-orange-800"><span className="material-symbols-outlined">arrow_back</span>Change details</button><h2 className="mt-10 font-display text-[38px] font-semibold text-neutral-ink md:text-[31px]">Verify your phone</h2><p className="mt-3 text-[18px] text-neutral-copy">Enter the code sent to +92 {phone}.</p><input value={otp} onChange={(event) => setOtp(event.target.value.replace(/\D/g, '').slice(0, 6))} inputMode="numeric" autoFocus maxLength={6} className="mt-12 h-20 w-full rounded-xl border border-[#e0c0b1] bg-white px-5 text-center font-display text-[30px] tracking-[.45em] outline-none focus:border-orange-500" />{developmentOtp && <p className="mt-4 rounded-xl bg-orange-100/50 p-3 text-center text-sm text-orange-900">Development OTP: <b>{developmentOtp}</b></p>}{error && <p className="mt-4 text-center text-sm text-danger">{error}</p>}<div className="mt-10"><ContinueButton loading={loading} onClick={onSubmit}>Create account</ContinueButton></div></div>; }
