'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { apiClient, type ApiCategory, type ApiMenuItem } from '@/lib/apiClient';
import { useCartStore } from '@/lib/store/cartStore';
import { CustomerFooter, CustomerNavBar } from '@/components/ui';

const img = {
  burger: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB0VT6dlXqPh8NB5rsPO05DSAZ-oE-ZldozuKBI9fjxRhs69mxY3pLQpCPJXHvPrnSZZZE9lOXGI3x2qqLYUV1EBjS2ccWPvqV4FRs8q3n1ib_soXpLZ2mqzWWJfBlS9cNg-ZunAYO-fDv0zFxuOPaTFa3O3C3u2UJxchiEPT4bVp5u78VnHBNl8CSZ-IzKQhclHxSqvdicwZmbSSpKKyvSfZ7VXTPovOvedE-hRQ8Bh0lex6Bf0z881w',
  wings: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBihVrbGcHu8FWMbkI7jOjytTZrCQdc07gfGx1P1nVdrqjoOzRDo7-4RtSuAnZwu-f7x60cwJMS9Vcr12ODnnKsF2KAqpGVuEuVWl_x94E7k33welTOXqOhqJcAYwxH78WmTcGDPe6NhbvnXXkQhocyVFIL_0QvKuSXcfYdpCHOp24DR1gLNwrd6cxlRSOmJG-CuNPoEDzFnu--dXQvImr36i-C61FqXsoIqzaIkZ6PU6LvoEiz6JxFbA',
  pizza: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBUHWlZYFP9MwNBIX1whxjG6NC0YoTR255W4NyS8_tYstOWjWrTFKAhbTMmD1aZqnIp_54WYBr2VZyv6gkVutRWHlAQ5J1U-fplMrDzCOO_WAt-CV-84W8JCMwLW1ZOEAULA33rJSbXFqL6VOc8XkT08Y7-2Yq3q_dURrtDT_CeKc3hbbRMO1Cl4IFU4t7BMSnOPARO_BYCbgebfE2gCverQHyXnM-gvBbRjkHGwAPPCutcMWGTqkdeQQ',
  tacos: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDjqmPXvgtqOHQFeEVlKHSiDNBRSvwRYvAZ7eyCD4ajpXxqsYFoSSBqPw8-JCxjipy-bZxsoS2bm3MArt3sh5CFfnIHv0sLNvFYSTbrB4bX3yax0cI8JdFo_zRByBn3OQtcTcMA6gt8EvFxFnl9CrzR2jUlmJAUcUyJND7-t_o0Vs9bvbLmfjv__jYVTj5U3sb23N42gjgxoUBUzEM0gtjFvIsdpB28348D9-uqK94n9xKCBB5Y3OqOQA',
  rings: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCL6YdGKXwTz0TeF6uEd2Nyqu3fQ6rQsduu0zvH15yxK7Bs_kAEvSu6fiXAcDzDolp7FQ9dH62eXIpRSC1e0UJom2Y-MJMBUQ7OLPZGsMIzC49a4jhlpsAj6xhu5adzfEN9a9vDWoWdJnG8aLiOaF3fnNS7Gw5DTFonk2Uv3UT878HkEaioY9vESrIgCN9SlKsreKgDL7xNNRCyOgl9MHey0HJs4ZUpoxZGQomPJdebJLEvypFXr2sMEw',
  salad: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCdRov_SR7ELdNjZl-R853DQxaSyDoN28x7qkpsoYSJUNYUZlOyqJp6CPU_uaWIFe2rd01ZBaJN_8d6WNWUWs7CcpE90y1ide99kJ6_qHEhk67M19wpEEJB1teZvgthGBL70pNLwrWY7AUp3teXJ9ueUl44-Hw3Es0gg_DeMB1VdTHKOYj7pViQGSoQ94pB7UbsxzHwZfQ9j1GiX-P6DWf-fZERoCA0dJyn4edOSeT4Ol-XFNp393BkSg',
};
const fallback = [['Zinger Supreme', 'Classic crispy delight', 650, img.burger], ['Spicy Wings (6pc)', 'Hot & Tangy glaze', 550, img.wings], ['Pepperoni Feast', 'Extra cheese load', 1200, img.pizza], ['Fish Tacos', 'Fresh ocean flavors', 850, img.tacos], ['Crispy Rings', 'Jumbo batter fried', 400, img.rings], ['Power Salad', 'Healthy & Filling', 750, img.salad]].map(([name, description, price, imageUrl], index) => ({ _id: `menu-${index}`, name, description, price, imageUrl, spiceLevel: index % 2 ? 'Hot' : 'Medium', category: 'Fast Food', isAvailable: true, addOns: [] } as unknown as ApiMenuItem));
const names = ['Fast Food', 'Chinese Food', 'BBQ']; const money = (n: number) => `PKR ${n.toLocaleString('en-PK')}`;
const categoryName = (item: ApiMenuItem) => typeof item.category === 'string' ? item.category : item.category.name;

export default function MenuPage() {
  const [items, setItems] = useState<ApiMenuItem[]>(fallback); const [categories, setCategories] = useState<ApiCategory[]>([]); const [active, setActive] = useState('Fast Food'); const [query, setQuery] = useState(''); const [sort, setSort] = useState('Popularity'); const [spice, setSpice] = useState(''); const [maxPrice, setMaxPrice] = useState(2500); const [filtersOpen, setFiltersOpen] = useState(false); const [cartPulse, setCartPulse] = useState(false); const add = useCartStore((s) => s.add); const cart = useCartStore((s) => s.items);
  useEffect(() => { Promise.all([apiClient.get('/menu'), apiClient.get('/categories')]).then(([m, c]) => { if (m.data.data?.length) setItems(m.data.data); setCategories(c.data.data ?? []); }).catch(() => undefined); }, []);
  const availableNames = categories.length ? categories.map((c) => c.name) : names;
  const filtered = useMemo(() => { const output = items.filter((item) => (!active || categoryName(item) === active) && `${item.name} ${item.description}`.toLowerCase().includes(query.toLowerCase()) && item.price <= maxPrice && (!spice || item.spiceLevel?.toLowerCase() === spice.toLowerCase())); return [...output].sort((a, b) => sort === 'Price: Low to High' ? a.price - b.price : sort === 'Price: High to Low' ? b.price - a.price : a.name.localeCompare(b.name)); }, [items, active, query, maxPrice, spice, sort]);
  const cartCount = cart.reduce((sum, entry) => sum + entry.quantity, 0); const cartTotal = cart.reduce((sum, entry) => sum + entry.price * entry.quantity, 0);
  const handleAdd = (item: ApiMenuItem) => { add(item); setCartPulse(false); requestAnimationFrame(() => setCartPulse(true)); window.setTimeout(() => setCartPulse(false), 300); };
  return <main className="min-h-screen bg-neutral-canvas pb-36 text-neutral-ink md:pb-0">
    <CustomerNavBar onSearch={setQuery} />
    <div className="hidden md:flex"><aside className="min-h-[calc(100vh-80px)] w-[360px] shrink-0 bg-[#293240] p-8 text-white"><p className="text-body-sm font-semibold uppercase tracking-wide text-orange-800">Categories</p><div className="mt-3 space-y-2">{availableNames.map((name, i) => <button key={name} onClick={() => setActive(name)} className={`flex w-full items-center gap-4 rounded-xl px-5 py-4 text-left text-heading-sm transition ${active === name ? 'bg-[#445064]' : 'hover:bg-white/10'}`}><span className="material-symbols-outlined">{['fastfood', 'restaurant', 'outdoor_grill'][i] ?? 'restaurant'}</span>{name}</button>)}</div><div className="mt-8 border-t border-white/10 pt-8"><p className="text-body-sm font-semibold uppercase tracking-wide text-white/60">Spicy level</p>{['Mild', 'Medium', 'Hot'].map((level) => <label key={level} className="mt-4 flex cursor-pointer items-center gap-3 text-body"><input type="radio" name="spice" checked={spice === level} onChange={() => setSpice(level)} className="accent-orange-500" />{level}</label>)}<p className="mt-8 text-body-sm font-semibold uppercase tracking-wide text-white/60">Price range</p><input type="range" min="300" max="2500" value={maxPrice} onChange={(e) => setMaxPrice(Number(e.target.value))} className="mt-5 w-full accent-orange-500" /><div className="mt-2 flex justify-between text-body-sm text-white/80"><span>PKR 0</span><span>PKR {maxPrice}+</span></div></div><div className="mt-28 rounded-xl border border-orange-800/50 p-5"><p className="text-heading-sm">Are you a Merchant?</p><button className="mt-3 w-full rounded-xl bg-orange-800 py-3 font-semibold">View Partner Portal</button></div></aside><section className="min-w-0 flex-1 px-8 py-7"><div className="flex items-center justify-between border-b border-orange-800/15 pb-6"><div><h1 className="font-display text-3xl font-semibold">{active}</h1><p className="mt-1 text-body text-neutral-copy">Showing {filtered.length} delicious items in Karachi</p></div><select value={sort} onChange={(e) => setSort(e.target.value)} className="rounded-xl border border-orange-800/30 bg-white px-4 py-3 text-body"><option>Popularity</option><option>Price: Low to High</option><option>Price: High to Low</option></select></div><div className="mt-7 grid grid-cols-2 gap-8 xl:grid-cols-4">{filtered.map((item, index) => <DesktopCard key={item._id} item={item} index={index} onAdd={() => handleAdd(item)} />)}</div></section></div>
    <section className="md:hidden"><MobileTabs names={availableNames} active={active} setActive={setActive} /><div className="px-5 py-6"><h1 className="font-display text-heading-lg font-semibold">Delicious {active}</h1><div className="mt-6 grid grid-cols-2 gap-5">{filtered.map((item, index) => <MobileCard key={item._id} item={item} index={index} onAdd={() => handleAdd(item)} />)}</div></div></section>
    <button onClick={() => setFiltersOpen(!filtersOpen)} className="fixed bottom-36 right-5 z-40 grid size-14 place-items-center rounded-full bg-orange-800 text-white shadow-menu md:hidden"><span className="material-symbols-outlined">tune</span></button>{filtersOpen && <MobileFilters spice={spice} setSpice={setSpice} maxPrice={maxPrice} setMaxPrice={setMaxPrice} onClose={() => setFiltersOpen(false)} />}
    {cartPulse && <div role="status" className="fixed bottom-40 left-1/2 z-50 -translate-x-1/2 rounded-full bg-neutral-ink px-4 py-2 text-body-sm font-semibold text-white shadow-float md:hidden">Added to cart</div>}
    {cartCount > 0 && <Link href="/cart" className="fixed bottom-20 left-5 right-5 z-40 flex h-16 items-center justify-between rounded-xl bg-orange-800 px-5 text-white shadow-menu md:hidden"><span className="flex items-center gap-3 text-body-sm font-semibold"><span className="material-symbols-outlined">shopping_bag</span>{cartCount} {cartCount === 1 ? 'Item' : 'Items'} • {money(cartTotal)}</span><span className="flex items-center gap-1 text-body-sm font-bold uppercase">View Cart <span className="material-symbols-outlined">chevron_right</span></span></Link>}
    <CustomerFooter />
  </main>;
}

function DesktopHeader({ query, setQuery, cartCount }: { query: string; setQuery: (v: string) => void; cartCount: number }) { return <header className="hidden h-20 items-center justify-between border-b border-neutral-border bg-neutral-canvas px-8 md:flex"><div className="flex items-center gap-12"><Link href="/" className="font-display text-3xl font-bold text-orange-800">Orange</Link><nav className="flex gap-8 text-heading-sm"><span className="border-b-2 border-orange-800 py-4 font-semibold text-orange-800">Karachi</span><span>Lahore</span><span>Islamabad</span></nav></div><div className="flex items-center gap-7"><label className="relative"><span className="material-symbols-outlined absolute left-4 top-1/2 -translate-y-1/2 text-neutral-copy">search</span><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search for food..." className="w-80 rounded-full bg-[#e4ebfa] py-3 pl-12 pr-5 outline-none focus:ring-2 focus:ring-orange-500" /></label><Link href="/cart" className="relative"><span className="material-symbols-outlined text-3xl">shopping_cart</span>{cartCount > 0 && <span className="absolute -right-3 -top-2 grid size-5 place-items-center rounded-full bg-orange-500 text-[10px] text-white">{cartCount}</span>}</Link><span className="material-symbols-outlined text-3xl">notifications</span><span className="grid size-11 place-items-center rounded-full bg-orange-100 text-orange-800"><span className="material-symbols-outlined">person</span></span></div></header>; }
function MobileHeader() { return <header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-neutral-border bg-neutral-canvas px-8 md:hidden"><Link href="/" className="font-display text-3xl font-bold text-orange-800">Orange</Link><div className="flex gap-6 text-orange-800"><span className="material-symbols-outlined">search</span><span className="material-symbols-outlined">notifications</span></div></header>; }
function MobileTabs({ names, active, setActive }: { names: string[]; active: string; setActive: (name: string) => void }) { return <nav className="sticky top-16 z-20 flex h-14 items-center justify-around border-b border-orange-800/15 bg-neutral-canvas shadow-sm">{names.slice(0, 3).map((name) => <button key={name} onClick={() => setActive(name)} className={`relative h-full px-2 text-body-sm font-semibold ${active === name ? 'text-orange-800' : 'text-neutral-copy'}`}>{name}{active === name && <span className="absolute bottom-0 left-1/2 h-[3px] w-7 -translate-x-1/2 rounded-full bg-orange-800" />}</button>)}</nav>; }
function DesktopCard({ item, index, onAdd }: { item: ApiMenuItem; index: number; onAdd: () => void }) { return <article className="overflow-hidden rounded-2xl bg-white shadow-card"><Link href={`/menu/${item._id}`}><div className="relative aspect-[16/9]"><img src={item.imageUrl} alt={item.name} className="size-full object-cover" />{index === 0 && <span className="absolute left-4 top-4 rounded-full bg-orange-500 px-3 py-2 text-caption font-bold">BEST SELLER</span>}{index === 2 && <span className="absolute left-4 top-4 rounded-full bg-neutral-blue px-3 py-2 text-caption font-bold">NEW</span>}</div></Link><div className="p-5"><div className="flex items-start justify-between gap-2"><h2 className="font-display text-heading-lg font-semibold leading-tight">{item.name}</h2><span className="shrink-0 text-body-sm font-bold text-orange-800">☆ {(4.2 + (index % 7) / 10).toFixed(1)}</span></div><p className="mt-3 min-h-12 text-body text-neutral-copy line-clamp-2">{item.description}</p><div className="mt-5 flex items-center justify-between"><strong className="font-display text-heading-lg text-orange-800">Rs. {item.price}</strong><button onClick={onAdd} aria-label={`Add ${item.name}`} className="grid size-12 place-items-center rounded-full bg-orange-500 text-3xl text-white shadow-float transition hover:bg-orange-800 active:scale-90">+</button></div></div></article>; }
function MobileCard({ item, index, onAdd }: { item: ApiMenuItem; index: number; onAdd: () => void }) { return <article className="overflow-hidden rounded-xl bg-white shadow-card"><Link href={`/menu/${item._id}`}><div className="relative aspect-square"><img src={item.imageUrl} alt={item.name} className="size-full object-cover" />{index === 0 && <span className="absolute right-2 top-2 rounded-full bg-orange-800 px-2 py-1 text-[10px] font-bold text-white">TOP RATED</span>}{index === 2 && <span className="absolute right-2 top-2 rounded-full bg-[#3d4756] px-2 py-1 text-[10px] font-bold text-white">CHEF&apos;S CHOICE</span>}</div></Link><div className="p-4"><h2 className="truncate text-body-sm font-semibold">{item.name}</h2><p className="mt-1 truncate text-body-sm text-neutral-copy">{item.description}</p><div className="mt-3 flex items-center justify-between"><strong className="font-display text-heading-md text-orange-800">{money(item.price)}</strong><button onClick={onAdd} aria-label={`Add ${item.name}`} className="grid size-10 place-items-center rounded-lg bg-orange-500 text-2xl text-white active:scale-90">+</button></div></div></article>; }
function MobileFilters({ spice, setSpice, maxPrice, setMaxPrice, onClose }: { spice: string; setSpice: (v: string) => void; maxPrice: number; setMaxPrice: (v: number) => void; onClose: () => void }) { return <div className="fixed inset-0 z-50 bg-black/35 p-5 md:hidden"><div className="absolute bottom-0 left-0 right-0 rounded-t-2xl bg-white p-6"><div className="flex items-center justify-between"><h2 className="font-display text-heading-lg">Filters</h2><button onClick={onClose}><span className="material-symbols-outlined">close</span></button></div><p className="mt-5 text-body-sm font-semibold">Spice level</p><div className="mt-3 flex gap-2">{['Mild', 'Medium', 'Hot'].map((level) => <button key={level} onClick={() => setSpice(level)} className={`rounded-full px-4 py-2 text-body-sm ${spice === level ? 'bg-orange-500 text-white' : 'bg-neutral-soft'}`}>{level}</button>)}</div><p className="mt-6 text-body-sm font-semibold">Maximum price: PKR {maxPrice}</p><input type="range" min="300" max="2500" value={maxPrice} onChange={(e) => setMaxPrice(Number(e.target.value))} className="mt-3 w-full accent-orange-500" /><button onClick={onClose} className="mt-6 w-full rounded-xl bg-orange-500 py-3 font-semibold text-white">Apply filters</button></div></div>; }
function MobileBottom({ active, cartCount }: { active: string; cartCount: number }) { const links = [['Home', 'home', '/'], ['Menu', 'restaurant_menu', '/menu'], ['Cart', 'shopping_cart', '/cart'], ['Orders', 'receipt_long', '/profile/orders'], ['Profile', 'person', '/profile']]; return <nav className="fixed bottom-0 left-0 right-0 z-50 flex h-16 items-center justify-around rounded-t-xl bg-white shadow-header md:hidden">{links.map(([label, icon, href]) => <Link key={label} href={href} className={`relative flex flex-col items-center rounded-xl px-2 py-1 text-caption font-semibold ${active === label ? 'bg-orange-500 text-orange-900' : 'text-neutral-copy'}`}><span className="material-symbols-outlined">{icon}</span>{label}{label === 'Cart' && cartCount > 0 && <span className="absolute right-1 top-0 size-2 rounded-full bg-orange-800" />}</Link>)}</nav>; }
function DesktopFooter() { return <footer className="hidden border-t border-neutral-border bg-[#edf2ff] px-8 py-12 text-center text-body text-neutral-copy md:block"><div className="flex items-center justify-between"><strong className="font-display text-heading-lg text-orange-800">Orange</strong><div className="flex gap-8"><span>About Us</span><span>Terms of Service</span><span>Privacy Policy</span><span>Contact Support</span></div></div><p className="mt-10">© 2024 Orange Food Pakistan. All rights reserved.</p></footer>; }
