'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import { categories, dishes, type Category } from '@/lib/mockData';

const icon = (name: string, classes = '') => <span className={`material-symbols-outlined ${classes}`}>{name}</span>;
const money = (price: number) => `Rs ${price.toLocaleString('en-PK')}`;
type Filter = 'All Favorites' | Category;

export default function Favorites() {
  const [filter, setFilter] = useState<Filter>('All Favorites'); const [query, setQuery] = useState(''); const [saved, setSaved] = useState(() => new Set(dishes.filter((dish) => dish.popular).map((dish) => dish.id)));
  const favorites = useMemo(() => dishes.filter((dish) => saved.has(dish.id) && (filter === 'All Favorites' || dish.category === filter) && `${dish.name} ${dish.restaurant}`.toLowerCase().includes(query.toLowerCase())), [filter, query, saved]);
  const remove = (id: string) => setSaved((current) => { const next = new Set(current); next.delete(id); return next; });
  return <main className="min-h-screen bg-[#f9f9ff] pb-24 text-neutral-ink"><FavoriteHeader /><section className="mx-auto max-w-[1600px] px-4 py-9 md:px-12 md:py-14"><div className="hidden md:block"><h1 className="font-display text-[57px] font-semibold tracking-tight">Your Favorites</h1><p className="mt-3 text-[25px] text-neutral-muted">Handpicked delights from Karachi&apos;s finest kitchens.</p><DesktopFilters filter={filter} setFilter={setFilter} /></div><div className="md:hidden"><h1 className="font-display text-[28px] font-medium">Your Favorites</h1><p className="mt-2 text-sm leading-6 text-neutral-copy">Quickly reorder your most loved dishes.</p><label className="mt-6 flex h-12 items-center gap-3 rounded-xl border border-[#e0c0b1] bg-white px-4 text-neutral-copy focus-within:border-orange-500"><span className="material-symbols-outlined text-[22px]">search</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search saved items" className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-[#667085]" /></label></div><div className="mt-8 grid grid-cols-2 gap-3 md:mt-16 md:grid-cols-2 md:gap-5 lg:grid-cols-4">{favorites.map((dish) => <FavoriteCard key={dish.id} dish={dish} onRemove={() => remove(dish.id)} />)}</div>{!favorites.length && <div className="mt-16 rounded-2xl bg-white p-12 text-center text-neutral-copy">No saved dishes match your search.</div>}</section><DesktopFooter /><MobileNav /></main>;
}
function FavoriteHeader() { return <header className="flex h-[72px] items-center justify-between border-b border-neutral-border/40 bg-[#f9f9ff] px-4 shadow-card md:px-8"><Link href="/" className="font-display text-[30px] font-bold text-orange-800">Orange</Link><nav className="hidden items-center gap-12 text-[18px] md:flex"><a>Lahore</a><a className="border-b-2 border-orange-800 py-2 font-semibold text-orange-800">Karachi</a><a>Islamabad</a></nav><div className="flex items-center gap-3 text-orange-800"><Link href="/cart" aria-label="Cart">{icon('shopping_cart', 'text-[28px]')}</Link><Link href="/profile" aria-label="Profile" className="grid size-11 place-items-center rounded-full bg-orange-100 text-orange-800">{icon('person', 'text-[25px]')}</Link></div></header>; }
function DesktopFilters({ filter, setFilter }: { filter: Filter; setFilter: (filter: Filter) => void }) { const filters: Filter[] = ['All Favorites', ...categories.map((category) => category.name)]; return <div className="mt-14 flex gap-5">{filters.map((value) => <button key={value} onClick={() => setFilter(value)} className={`rounded-full px-8 py-3 text-[17px] font-semibold ${filter === value ? 'bg-orange-500 text-neutral-ink' : 'bg-[#e2e8f8] text-neutral-muted'}`}>{value === 'All Favorites' ? value : value === 'Chinese Food' ? 'Chinese' : value}</button>)}</div>; }
function FavoriteCard({ dish, onRemove }: { dish: typeof dishes[number]; onRemove: () => void }) { return <article className="relative flex min-w-0 flex-col overflow-hidden rounded-xl bg-white shadow-card md:block md:rounded-2xl"><div className="relative aspect-square overflow-hidden md:h-[200px] md:aspect-auto md:w-full"><img src={dish.image} alt={dish.name} className="size-full object-cover" /><button onClick={onRemove} aria-label={`Remove ${dish.name} from favorites`} className="absolute right-2 top-2 grid size-9 place-items-center rounded-full bg-white text-orange-800 shadow-card md:right-5 md:top-5 md:size-14">{icon('favorite', 'text-[18px] md:text-[27px]')}</button></div><div className="flex min-h-[118px] min-w-0 flex-1 flex-col p-3 md:p-6"><h2 className="line-clamp-2 font-display text-sm font-semibold leading-5 md:text-[26px] md:leading-9">{dish.name}</h2><p className="mt-1 truncate text-xs text-neutral-copy md:hidden">{dish.restaurant}</p><p className="mt-3 hidden min-h-[52px] text-[17px] leading-6 text-neutral-copy md:block">{dish.description}</p><div className="mt-auto flex items-center justify-between gap-1"><p className="text-sm font-semibold text-orange-800 md:text-[25px]">{money(dish.price)}</p><button aria-label={`Add ${dish.name} to cart`} className="grid size-10 place-items-center rounded-lg bg-orange-500 text-white shadow-float active:scale-90 md:hidden">{icon('add', 'text-[22px]')}</button></div></div></article>; }
function DesktopFooter() { return <footer className="mt-32 hidden bg-[#eef2ff] py-14 text-center md:block"><h2 className="font-display text-[26px] font-semibold text-orange-800">Orange Food Pakistan</h2><div className="mt-8 flex justify-center gap-9 underline"><a>About Us</a><a>Terms of Service</a><a>Privacy Policy</a><a>Contact Support</a></div><p className="mt-9 text-neutral-copy">© 2026 Orange Cloud Kitchen. All rights reserved.</p></footer>; }
function MobileNav() { return <nav className="fixed inset-x-0 bottom-0 z-30 flex h-[76px] items-center justify-around rounded-t-2xl bg-white shadow-header md:hidden"><Link href="/" className="flex flex-col items-center gap-1 text-neutral-copy">{icon('home', 'text-[24px]')}<span className="text-xs">Home</span></Link><Link href="/menu" className="flex flex-col items-center gap-1 text-neutral-copy">{icon('restaurant_menu', 'text-[24px]')}<span className="text-xs">Menu</span></Link><Link href="/profile/orders" className="flex flex-col items-center gap-1 text-neutral-copy">{icon('receipt_long', 'text-[24px]')}<span className="text-xs">Orders</span></Link><Link href="/profile" className="flex flex-col items-center gap-1 rounded-xl bg-orange-500 px-4 py-2 text-orange-900">{icon('person', 'text-[24px]')}<span className="text-xs">Profile</span></Link></nav>; }
