'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useEffect, useRef, useState } from 'react';
import { apiClient, apiError } from '@/lib/apiClient';
import { CustomerFooter, CustomerNavBar } from '@/components/ui';
import { useCartStore } from '@/lib/store/cartStore';
import { useAuthStore } from '@/lib/store/authStore';

const DELIVERY_AREAS = ['Malir Saudabad', 'Malir Khokrapar', 'Malir Memon Goth', 'Malir Model Colony', 'Malir Cantt', 'Shah Faisal Colony', 'Jinnah Square', 'Airport Side', 'Kala Board', 'Quaidabad', 'Jaffar Tayyar', 'Gulshan-e-Iqbal', 'Gulistan-e-Johar', 'Safoora Goth & Chowrangi', 'Scheme 33', 'University Road', 'Askari IV', 'Malir Halt', 'Rafa-e-Aam Society', 'Wireless Gate', 'Shamsi Society'] as const;
type Address = { house: string; street: string; area: string; landmark: string; name: string; phone: string };
const emptyAddress: Address = { house: '', street: '', area: '', landmark: '', name: '', phone: '' };
const icon = (name: string, classes = '') => <span className={`material-symbols-outlined ${classes}`}>{name}</span>;
const money = (value: number) => `Rs. ${value.toLocaleString('en-PK')}`;

export default function CheckoutPage() {
  const router = useRouter(); const { items, clear } = useCartStore(); const accessToken = useAuthStore((state) => state.accessToken);
  const [payment, setPayment] = useState<'Cash on Delivery' | 'Credit/Debit Card'>('Cash on Delivery'); const [slot, setSlot] = useState('ASAP'); const [promo, setPromo] = useState(''); const [error, setError] = useState(''); const [placing, setPlacing] = useState(false); const [address, setAddress] = useState<Address>(emptyAddress);
  const checkoutId = useRef(typeof crypto !== 'undefined' ? crypto.randomUUID() : `${Date.now()}-${Math.random().toString(36).slice(2)}`);
  const subtotal = items.reduce((sum, item) => sum + item.price * item.quantity, 0); const delivery = items.length ? 99 : 0; const tax = Math.round(subtotal * .16); const discount = promo.trim().toUpperCase() === 'OFFER50' ? 150 : 0; const total = Math.max(0, subtotal + delivery + tax - discount);

  useEffect(() => { if (!accessToken) router.replace('/login'); }, [accessToken, router]);
  const placeOrder = async () => {
    if (!items.length || placing) return;
    const missing = !address.house.trim() || !address.street.trim() || !address.area || !address.name.trim() || !address.phone.trim();
    if (missing) { setError('Please complete every required delivery field.'); return; }
    setPlacing(true); setError('');
    try {
      const deliveryAddress = `${address.house.trim()}, ${address.street.trim()}, ${address.area}, Karachi${address.landmark.trim() ? `, Landmark: ${address.landmark.trim()}` : ''}, Contact: ${address.name.trim()} ${address.phone.trim()}`;
      const response = await apiClient.post('/orders', { items: items.map((item) => ({ item: item._id, quantity: item.quantity, customizations: [slot] })), deliveryAddress, deliveryArea: address.area, paymentMethod: payment }, { headers: { 'Idempotency-Key': checkoutId.current } });
      clear(); router.push(`/order-confirmation/${response.data.data._id}`);
    } catch (requestError) { setError(apiError(requestError)); } finally { setPlacing(false); }
  };

  return <main className="min-h-screen bg-[#f9f9ff] text-neutral-ink"><CustomerNavBar /><div className="mx-auto max-w-[1240px] px-5 py-6 md:px-6 md:py-8"><h1 className="hidden font-display text-[28px] font-semibold md:block">Checkout</h1><MobileSteps /><div className="mt-6 grid gap-6 lg:grid-cols-[minmax(0,1fr)_360px]"><section className="space-y-6"><AddressCard address={address} setAddress={setAddress} /><DeliveryTime slot={slot} setSlot={setSlot} /><PaymentMethods payment={payment} setPayment={setPayment} /><MobileOrderSummary items={items} subtotal={subtotal} delivery={delivery} tax={tax} total={total} /></section><DesktopOrderSummary items={items} subtotal={subtotal} delivery={delivery} tax={tax} discount={discount} total={total} promo={promo} setPromo={setPromo} onPlace={placeOrder} placing={placing} /></div>{error && <p role="alert" className="mt-5 rounded-xl bg-danger/10 p-3 text-danger">{error}</p>}</div><CustomerFooter /><MobileOrderBar total={total} onPlace={placeOrder} placing={placing} /></main>;
}

function MobileSteps() { return <div className="mx-auto flex max-w-md items-center justify-between px-2 md:hidden">{[['1', 'Address'], ['2', 'Payment'], ['3', 'Review']].map(([number, label], index) => <div key={label} className="flex flex-1 items-center last:flex-none"><div className="flex flex-col items-center gap-1"><span className={`grid size-8 place-items-center rounded-full text-sm font-bold ${index < 2 ? 'bg-orange-800 text-white' : 'bg-[#dce2f3] text-neutral-copy'}`}>{number}</span><span className={`text-sm ${index < 2 ? 'font-semibold text-orange-800' : 'text-neutral-copy'}`}>{label}</span></div>{index < 2 && <span className={`mx-2 mt-[-20px] h-0.5 flex-1 ${index === 0 ? 'bg-orange-800' : 'bg-[#dce2f3]'}`} />}</div>)}</div>; }

function AddressCard({ address, setAddress }: { address: Address; setAddress: React.Dispatch<React.SetStateAction<Address>> }) { const set = (field: keyof Address, value: string) => setAddress((current) => ({ ...current, [field]: value })); return <section className="rounded-xl border border-[#d6e0f3] bg-white p-4 shadow-card"><div className="flex gap-3"><span className="grid size-10 place-items-center rounded-lg bg-orange-100/50 text-orange-500">{icon('location_on', 'text-[22px]')}</span><div><h2 className="font-display text-[20px] font-semibold">Delivery Address</h2><p className="text-[13px] text-neutral-copy">We deliver only to the listed Karachi areas.</p></div></div><div className="mt-4 grid gap-3 md:grid-cols-2"><Field required label="House / Flat no." value={address.house} onChange={(value) => set('house', value)} /><Field required label="Street / Road" value={address.street} onChange={(value) => set('street', value)} /><label className="block md:col-span-2"><span className="mb-2 block text-sm font-semibold text-neutral-copy">Delivery area <span className="text-danger">*</span></span><select required value={address.area} onChange={(event) => set('area', event.target.value)} className="h-12 w-full rounded-lg border border-[#e0c0b1] bg-white px-4 outline-none focus:border-orange-800 focus:ring-2 focus:ring-orange-500/20"><option value="" disabled>Select your delivery area</option>{DELIVERY_AREAS.map((area) => <option key={area} value={area}>{area}</option>)}</select></label><Field label="Landmark (optional)" value={address.landmark} onChange={(value) => set('landmark', value)} /><div className="hidden md:block" /><Field required label="Contact name" value={address.name} onChange={(value) => set('name', value)} /><Field required label="Phone number" type="tel" value={address.phone} onChange={(value) => set('phone', value)} /></div></section>; }

function Field({ label, value, onChange, type = 'text', required = false }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean }) { return <label className="block"><span className="mb-2 block text-sm font-semibold text-neutral-copy">{label}{required && <span className="text-danger"> *</span>}</span><input required={required} value={value} onChange={(event) => onChange(event.target.value)} type={type} className="h-12 w-full rounded-lg border border-[#e0c0b1] bg-white px-4 outline-none focus:border-orange-800 focus:ring-2 focus:ring-orange-500/20" /></label>; }

function DeliveryTime({ slot, setSlot }: { slot: string; setSlot: (slot: string) => void }) { const choices = [['ASAP', '25 - 35 mins'], ['Schedule', 'Today, 8:00 PM'], ['Late Night', 'Today, 11:30 PM']]; return <section className="hidden rounded-xl border border-[#d6e0f3] bg-white p-4 shadow-card md:block"><div className="flex gap-3"><span className="grid size-10 place-items-center rounded-lg bg-orange-100/50 text-orange-500">{icon('schedule', 'text-[22px]')}</span><div><h2 className="font-display text-[20px] font-semibold">Delivery Time</h2><p className="text-[13px] text-neutral-copy">Select your preferred slot</p></div></div><div className="mt-4 grid grid-cols-3 gap-3">{choices.map(([name, detail]) => <button type="button" key={name} onClick={() => setSlot(name)} className={`rounded-xl border px-2 py-3 text-center text-sm ${slot === name ? 'border-2 border-orange-800 bg-orange-100/30 text-orange-800' : 'border-[#d6e0f3]'}`}><b className="block">{name}</b><span className="mt-1 block text-[12px]">{detail}</span></button>)}</div></section>; }

function PaymentMethods({ payment, setPayment }: { payment: 'Cash on Delivery' | 'Credit/Debit Card'; setPayment: (method: 'Cash on Delivery' | 'Credit/Debit Card') => void }) { const methods: Array<['Cash on Delivery' | 'Credit/Debit Card', string, string]> = [['Cash on Delivery', 'Pay when you receive', 'payments'], ['Credit/Debit Card', 'Visa, Mastercard, PayPak', 'credit_card']]; return <section className="rounded-xl border border-[#d6e0f3] bg-white p-4 shadow-card"><div className="hidden gap-3 md:flex"><span className="grid size-10 place-items-center rounded-lg bg-orange-100/50 text-orange-500">{icon('payments', 'text-[22px]')}</span><div><h2 className="font-display text-[20px] font-semibold">Payment Method</h2><p className="text-[13px] text-neutral-copy">Choose cash or card payment.</p></div></div><h2 className="mb-3 font-display text-[20px] font-semibold md:hidden">Payment Method</h2><div className="grid gap-2.5 md:mt-4 md:grid-cols-2">{methods.map(([name, detail, paymentIcon]) => <button type="button" key={name} onClick={() => setPayment(name)} className={`flex min-h-[68px] items-center gap-3 rounded-xl border p-3 text-left ${payment === name ? 'border-2 border-orange-800 bg-orange-100/30' : 'border-[#e0c0b1]/50'}`}><span className="grid size-8 place-items-center rounded-lg bg-[#e2e8f8] text-orange-800">{icon(paymentIcon)}</span><span className="min-w-0 flex-1"><b className="block text-sm">{name}</b><span className="block text-[12px] text-neutral-copy">{detail}</span></span><span className={`grid size-4 place-items-center rounded-full border-2 ${payment === name ? 'border-orange-800' : 'border-[#e0c0b1]'}`}>{payment === name && <span className="size-2 rounded-full bg-orange-800" />}</span></button>)}</div></section>; }

function Items({ items }: { items: ReturnType<typeof useCartStore.getState>['items'] }) { return <div className="space-y-4">{items.map((item) => <div key={item._id} className="flex items-start justify-between gap-3"><div className="flex gap-4"><img src={item.imageUrl} alt="" className="size-16 rounded-lg object-cover" /><div><p className="font-semibold">{item.name}</p><p className="text-sm text-neutral-copy">Qty: {item.quantity}</p></div></div><b className="text-[18px]">{money(item.price * item.quantity)}</b></div>)}</div>; }
function MobileOrderSummary({ items, subtotal, delivery, tax, total }: { items: ReturnType<typeof useCartStore.getState>['items']; subtotal: number; delivery: number; tax: number; total: number }) { return <section className="md:hidden"><h2 className="mb-3 font-display text-[20px] font-semibold">Order Summary</h2><div className="overflow-hidden rounded-xl border border-[#e0c0b1]/30 bg-white shadow-card"><div className="p-4"><Items items={items} /></div><Totals subtotal={subtotal} delivery={delivery} tax={tax} total={total} compact /></div></section>; }
function DesktopOrderSummary({ items, subtotal, delivery, tax, discount, total, promo, setPromo, onPlace, placing }: { items: ReturnType<typeof useCartStore.getState>['items']; subtotal: number; delivery: number; tax: number; discount: number; total: number; promo: string; setPromo: (promo: string) => void; onPlace: () => void; placing: boolean }) { return <aside className="hidden h-fit overflow-hidden rounded-xl border border-[#d6e0f3] bg-white shadow-float lg:block"><div className="bg-[#eef2ff] p-5"><h2 className="font-display text-[22px] font-semibold">Order Summary</h2><p className="mt-1 text-sm text-neutral-copy">{items.length} items from <b className="text-orange-800">Orange</b></p></div><div className="p-5"><Items items={items} /><div className="my-5 border-t border-[#dce2f3]" /><div className="flex gap-2"><input value={promo} onChange={(event) => setPromo(event.target.value)} placeholder="Promo Code" className="min-w-0 flex-1 rounded-lg border border-[#d6e0f3] px-3 py-2 text-sm outline-none" /><button type="button" className="rounded-lg bg-neutral-ink px-4 text-sm text-white">Apply</button></div><div className="mt-5"><Totals subtotal={subtotal} delivery={delivery} tax={tax} discount={discount} total={total} /><button type="button" onClick={onPlace} disabled={!items.length || placing} className="mt-6 flex h-14 w-full items-center justify-center gap-3 rounded-xl bg-orange-500 font-display text-[18px] font-semibold text-white shadow-lg disabled:opacity-50">{placing ? 'Placing order…' : 'Place Order'} {icon('arrow_forward')}</button></div></div></aside>; }
function Totals({ subtotal, delivery, tax, discount = 0, total, compact = false }: { subtotal: number; delivery: number; tax: number; discount?: number; total: number; compact?: boolean }) { return <div className={`${compact ? 'bg-[#f0f3ff] p-4' : ''} space-y-2.5 text-sm text-neutral-copy`}><div className="flex justify-between"><span>Subtotal</span><span>{money(subtotal)}</span></div><div className="flex justify-between"><span>Delivery Fee</span><span className="text-orange-800">{money(delivery)}</span></div><div className="flex justify-between"><span>{compact ? 'Service Fee' : 'GST (16%)'}</span><span>{money(tax)}</span></div>{discount > 0 && <div className="flex justify-between text-danger"><span>Discount (OFFER50)</span><span>- {money(discount)}</span></div>}<div className="flex justify-between border-t border-dashed border-[#d6e0f3] pt-3 font-display text-[21px] font-semibold text-neutral-ink"><span>Total</span><span className="text-orange-800">{money(total)}</span></div></div>; }
function MobileOrderBar({ total, onPlace, placing }: { total: number; onPlace: () => void; placing: boolean }) { return <div className="fixed inset-x-0 bottom-0 z-50 border-t border-neutral-border bg-white p-3 md:hidden"><div className="flex items-center gap-4"><div><span className="text-[12px] text-neutral-copy">Total Amount</span><b className="block font-display text-[19px] text-orange-800">{money(total)}</b></div><button type="button" onClick={onPlace} disabled={placing} className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-orange-500 py-3 font-display text-[17px] font-semibold text-white shadow-lg">{placing ? 'Placing…' : 'Place Order'} {icon('chevron_right')}</button></div></div>; }
